spring:
  datasource:
    url: "jdbc:h2:mem:se452db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    driverClassName: "org.h2.Driver"
  h2:
    console.enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true